#!/bin/bash
# chkconfig: 2345 81 19

killpstree(){ # http://qiita.com/_akisato/items/e10ba8fc57e5c4c08d8c
    local children=`ps --ppid $1 --no-heading | awk '{ print $1 }'`
    for child in $children
    do
        killpstree $child
    done
    kill $1
}

export NAME=hubot
export LOG_DIR=/var/log/${NAME}
export PID=/var/run/${NAME}.pid
export LOG=${LOG_DIR}/${NAME}.log
export -f killpstree
HUBOT_ROOT_DIR="/home/kuma/wanko" # you have to specify this in ABSOLUTE path!!

test -d $LOG_DIR || mkdir $LOG_DIR

case $1 in
  'start' )
    $0 status >/dev/null 2>&1 && echo "${NAME} is already running." && exit 1
    su - kuma -c "cd ${HUBOT_ROOT_DIR}; bin/${NAME} --adapter slack" 0<&- &> $LOG &
    echo $! > $PID 
    ;;
  'stop' )
    { $0 status >/dev/null 2>&1; } || { echo "${NAME} is not running." && exit 1; }
    test -f $PID && cat $PID | xargs -I % bash -c "killpstree %" && rm $PID
    ;;
  'restart' )
    $0 stop
    sleep 1
    $0 start
    ;;
  'status' )
    { test -f $PID; } || { echo "${NAME} not running." && exit 1; }
    PID=`cat $PID`
    kill -s 0 $PID >/dev/null 2>&1 && echo "${NAME} is running." && exit 0
    echo "${NAME} not running."
    exit 1
    ;;
  *)
    echo "Usage: $0 start|stop|restart|status"
    ;;
esac

